### PR TITLE
Export external-link

### PR DESCRIPTION
**Pull request by najisawas**

### CODE REVIEW

**Review by Raynos — APPROVED** [review]

**Comment by najisawas** [comment]
@Raynos do you happen to still have permissions for adding users to the npm package? It would be nice to be able to npm publish the update

**Comment by Raynos** [comment]
```
$ npm owner ls grafana-dash-gen
raynos <raynos2@gmail.com>
uber <opensource@uber.com>
```

The last time I touched this in 2017/2018 there was a wiki page with instructions on how to login as the `uber` npm user and then `npm owner add najisawas grafana-dash-gen` and then logout as the `uber` npm user.

Alternatively I can add someone to the package because I technically have permissions, but I probably should not have permissions at this stage.

**Comment by albertyw** [comment]
Send me permissions.  My npm username is `albertyw`.  The old wiki page about npm auth doesn't work anymore.

Alternatively, come back to Uber.

**Comment by najisawas** [comment]
yeah if you can add Albert and me, my username is `najisawas`.

Definitely vote you coming back as well lol

**Comment by Raynos** [comment]
I added `albertyw` ; he can add others as he sees fit.

**Pull request merged**
